routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/migrate', function () {
    $clearcache = Artisan::call('migrate');
    echo "migrate run<br>";

    $clearview = Artisan::call('view:clear');
    echo "View cleared<br>";

    $clearconfig = Artisan::call('config:cache');
    echo "Config cleared<br>";

    $cleardebugbar = Artisan::call('debugbar:clear');
    echo "Debug Bar cleared<br>";
});

Route::get('/logout', 'HomeController@logout')->name('logout-dash');
Route::get('/login', 'HomeController@index')->name('home');
Route::get('/', 'WebController@index');
Route::get('/projects-show', 'WebController@projectsShow')->name('projects-show');
Route::get('/profile', 'WebController@profile');
Route::get('/category/{id}', 'WebController@categoryDeatil')->name('category-detail');
Route::get('/profile/{id}', 'WebController@profile')->name('profile');

Route::get('/about-us', 'WebController@AboutUs')->name('about-us');
Route::get('/contact-us', 'WebController@ContactUs')->name('about-us');
Auth::routes();



Route::group(['as'=>'admin.','middleware'=>['auth','admin'],'prefix'=>'admin'],function (){

    Route::get('/sliders', 'AdminController@Slider')->name('sliders');
    Route::get('/sliders-create', 'AdminController@SliderCreate')->name('slider-create');
    Route::post('/create-sliders', 'AdminController@CreateSlider')->name('add-slider');
    Route::get('/delete-sliders/{id}', 'AdminController@DelSlider')->name('delete-slider');
    Route::get('/edit-sliders/{id}', 'AdminController@EditSlider')->name('edit-slider');
    Route::post('/edit-sliders/{id}', 'AdminController@UpdateSlider')->name('update-slider');


    Route::get('/projects', 'ProjctController@Project')->name('projects');
    Route::get('/projects-create', 'ProjctController@ProjectCreate')->name('project-create');
    Route::post('/create-projects', 'ProjctController@CreateProject')->name('add-project');
    Route::get('/delete-projects/{id}', 'ProjctController@DelProject')->name('delete-project');
    Route::get('/edit-projects/{id}', 'ProjctController@EditProject')->name('edit-project');
    Route::post('/edit-projects/{id}', 'ProjctController@UpdateProject')->name('update-project');



    Route::get('/dashboard','AdminController@dashboard')->name('dashboard');
    Route::get('category/delete/{id}','DeleteController@delCategory')->name('delete-category');
    Route::get('/labour','LabourController@createLabour')->name('labourcreate');
    Route::get('labour/delete/{id}','DeleteController@delLabour')->name('delete-labour');


    Route::post('labour/{id}','LabourController@uppdateLabour')->name('updateLabour');
    Route::resource('labour','LabourController');
    Route::get('/edit-labour/{id}','AdminController@editlabour')->name('editLabour');

    Route::resource('category','CategoryController');





});

app/Labour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Labour extends Model
{

}

app/Http/Controllers/LabourController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Labour;
use App\User;
use Illuminate\Http\Request;

class LabourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::where('role_id',0)->paginate(20);
        return view('admin.labours.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        dd('ok');
        $categories = Category::with('childrens')->get();
        return view('admin.labours.create', compact('categories'));
    }

    public function createLabour()
    {
        dd('ok');
        $categories = Category::with('childrens')->get();
        return view('admin.labours.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $file = $request->file('thumbnail');
        $destinationPath = 'assets/uploads/labour-pics';
        $filename = $file->getClientOriginalName();
        $filename = time() . $filename;
        $file->move($destinationPath, $filename);
        $request->merge(['img' => $filename]);

//        dd($request->all());
        $user=User::create($request->all());

        if($user){
            return  back()->with('message','Labour Added Successfully');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Labour  $labour
     * @return \Illuminate\Http\Response
     */
    public function show(Labour $labour)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Labour  $labour
     * @return \Illuminate\Http\Response
     */
//    public function edit(Labour $labour,$id)
//    {
////            dd('pl');
//        $user=User::find($id);
////        dd($user);
//        $categories=Category::all();
//        return view('admin.labours.edit',compact('categories','user'));
//    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Labour  $labour
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Labour $labour)
    {
        dd('update');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Labour  $labour
     * @return \Illuminate\Http\Response
     */
    public function destroy(Labour $labour)
    {
        //
    }

    public function uppdateLabour(Request $request,$id){

        $user=User::find($id);

        if ($file = $request->file('thumbnail')) {
            $destinationPath = 'assets/uploads/labour-pics';
            $filename = $file->getClientOriginalName();
            $filename = time() . $filename;
            $file->move($destinationPath, $filename);
            $request->merge(['img' => $filename]);

            @unlink(public_path('uploads/scholars/' . $user->picture));
        }

        $user->update($request->all());
        return  back()->with('message','user update Successfully');
    }
}

resources/views/admin/labours/create.blade.php
@extends('admin.layouts.app')
@section('content')
	<div class="main-content">
		<div class="main-content-inner">
			<div class="breadcrumbs ace-save-state" id="breadcrumbs">
				<ul class="breadcrumb">
					<li>
						<i class="ace-icon fa fa-home home-icon"></i>
						<a href="#">Home</a>
					</li>

					<li>
						<a href="{{route('admin.dashboard')}}">Dashboard</a>
					</li>
					<li class="active">Labour</li>
				</ul><!-- /.breadcrumb -->

				<div class="nav-search" id="nav-search">
					<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
					</form>
				</div><!-- /.nav-search -->
			</div>

			<div class="page-content">
				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="ace-icon fa fa-cog bigger-130"></i>
					</div>

					<div class="ace-settings-box clearfix" id="ace-settings-box">
						<div class="pull-left width-50">
							<div class="ace-settings-item">
								<div class="pull-left">
									<select id="skin-colorpicker" class="hide">
										<option data-skin="no-skin" value="#438EB9">#438EB9</option>
										<option data-skin="skin-1" value="#222A2D">#222A2D</option>
										<option data-skin="skin-2" value="#C6487E">#C6487E</option>
										<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
									</select>
								</div>
								<span>&nbsp; Choose Skin</span>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-navbar" autocomplete="off" />
								<label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-sidebar" autocomplete="off" />
								<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-breadcrumbs" autocomplete="off" />
								<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" autocomplete="off" />
								<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
								<label class="lbl" for="ace-settings-add-container">
									Inside
									<b>.container</b>
								</label>
							</div>
						</div><!-- /.pull-left -->

						<div class="pull-left width-50">
							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" autocomplete="off" />
								<label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" autocomplete="off" />
								<label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
							</div>

							<div class="ace-settings-item">
								<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" autocomplete="off" />
								<label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
							</div>
						</div><!-- /.pull-left -->
					</div><!-- /.ace-settings-box -->
				</div><!-- /.ace-settings-container -->

				<div class="page-header">
					<h1>
						Labour
						<small>
							<i class="ace-icon fa fa-angle-double-right"></i>
							Add Labour
						</small>
					</h1>
				</div><!-- /.page-header -->

				<div class="row">
					<div class="col-xs-12">
						<!-- PAGE CONTENT BEGINS -->
						<div class="row">
							<div class="col-xs-12">
								@if(Session::has('message'))
									<div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('message') !!}</em></div>
								@endif
								<div style="box-shadow: 2px 2px 2px 2px #ccc;" class="col-xs-12" class="card-body">

									<form  action="{{route('admin.labour.store')}}"  method="post" accept-charset="utf-8" enctype="multipart/form-data">
										<div class="row">
											@csrf
											<div class="col-lg-9">
												<div class="form-group row">
													<label style="margin-top:20px;" for="email" class="col-xs-12 col-form-label text-md-right">{{ __('First Name') }}</label>
													<div class="col-xs-12">
														<input id="email" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name"  required>
														@if ($errors->has('first_name'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('first_name') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>
												<div class="form-group row">
													<label for="email" class="col-xs-12 col-form-label text-md-right">{{ __('Last Name') }}</label>
													<div class="col-xs-12">
														<input id="email" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name"  required>
														@if ($errors->has('last_name'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('last_name') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>
												<div class="form-group row">
													<label for="email" class="col-xs-12 col-form-label text-md-right">{{ __('Email') }}</label>
													<div class="col-xs-12">
														<input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" >
														@if ($errors->has('email'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('email') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>
												<div class="form-group row">
													<label for="email" class="col-xs-12 col-form-label text-md-right">{{ __('Experience') }}</label>
													<div class="col-xs-12">
														<input id="email" type="number" class="form-control{{ $errors->has('experience') ? ' is-invalid' : '' }}" name="experience" >
														@if ($errors->has('experience'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('experience') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>

												<div class="form-group row">
													<div class="col-xs-6">
														<label class="form-control-label">Phone number</label>
														<input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" >
														@if ($errors->has('phone'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('phone') }}</strong>
                                    						</span>
														@endif
													</div>
													<div class="col-xs-6">
														<label class="form-control-label">CNIC Nmumber</label>
														<input id="phone" type="text" class="form-control{{ $errors->has('cnic') ? ' is-invalid' : '' }}" name="cnic"  >
														@if ($errors->has('cnic'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('cnic') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>

												<div class="form-group row">
													<label for="email" class="col-xs-12 col-form-label text-md-right">{{ __('Address') }}</label>
													<div class="col-xs-12">
														<textarea rows="5" id="email" type="number" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address"  required></textarea>
														@if ($errors->has('address'))
															<span class="invalid-feedback">
                                        					<strong>{{ $errors->first('address') }}</strong>
                                    						</span>
														@endif
													</div>
												</div>

											</div>
											<div class="col-lg-3">
												<ul class="list-group row">
													<li class="list-group-item active"><h5>Labour Image</h5></li>
													<li class="list-group-item">
														<div class="mb-3">
															<div class="custom-file ">
																{{--<input type="file"  class="custom-file-input" name="thumbnail" id="id-input-file-2">--}}
																<input aria-required="true" type="file" multiple  class="custom-file-input" name="thumbnail" id="id-input-file-2" required>
																{{--<label class="custom-file-label" for="thumbnail">Choose file</label>--}}
															</div>
														</div>
														<div class="img-thumbnail text-center">
															<img src="@if(isset($user)) {{asset('assets/uploads/labour-pics/'.$user->img)}} @else {{asset('assets/images/no-thumbnail.jpeg')}} @endif" id="imgthumbnail" class="img-thumbnail" alt="">
														</div>
													</li>

													{{--@php--}}
														{{--$ids = (isset($product) && $product->categories->count() > 0 ) ? array_pluck($product->categories->toArray(), 'id') : null;--}}
													{{--@endphp--}}
													<li class="list-group-item active"><h5>Select Categories</h5></li>
													<li class="list-group-item ">
														<select name="cat_id" id="" class=" form-control"  required autofocus>
															<option  value="" hidden>Select Category</option>
															@if($categories->count() > 0)

																@foreach($categories as $category)
																	<option value="{{$category->id}}"
																	{{--@if(!is_null($ids) && in_array($category->id, $ids))--}}
																		{{--{{'selected'}}--}}
																			{{--@endif--}}
																	>{{$category->title}}</option>
																@endforeach
															@endif
														</select>
													</li>
												</ul>

                                                <div class="form-group row mb-0">
                                                    <div class="col-xs-12">
                                                        <input type="submit" class="btn btn-primary" value="Save Labour">
                                                    </div>
                                                </div>
											</div>
										</div>
									</form>

								</div>
							</div><!-- /.span -->
						</div><!-- /.row -->

						<div class="hr hr-18 dotted hr-double"></div>

						<!-- PAGE CONTENT ENDS -->
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.page-content -->
		</div>
	</div>
@endsection

@section('script')
	<script>
        $('#summernote').summernote({
            height: 100
        });


        //        $(".select").chosen({max_selected_options: 5});
        $(".select").chosen({width: "100%"});

        $('.slugify').keyup(function () {
            var url=($(this)).val();
//          str = url.split(" ").join("-").toLowerCase();
            str = url.replace(/\s+/g, '-').toLowerCase();
            $('#slug-text').text(str);
            $('#slug_title').val(str);
        });

        //        $('#title').on('keyup',(function () {
        //            $('#slug-text').text('ok');
        //        });
        $(document).ready(function () {
            setTimeout(function() {
                $('.alert-success').fadeOut('slow');
            }, 3000);
        });

        $('#id-input-file-2').on('change', function() {
            var file = $(this).get(0).files;
            var reader = new FileReader();
            reader.readAsDataURL(file[0]);
            reader.addEventListener("load", function(e) {
                var image = e.target.result;
                $("#imgthumbnail").attr('src', image);
            });
        });



	</script>

@endsection