routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/migrate', function () {
    $clearcache = Artisan::call('migrate');
    echo "migrate run<br>";

    $clearview = Artisan::call('view:clear');
    echo "View cleared<br>";

    $clearconfig = Artisan::call('config:cache');
    echo "Config cleared<br>";

    $cleardebugbar = Artisan::call('debugbar:clear');
    echo "Debug Bar cleared<br>";
});

Route::get('/logout', 'HomeController@logout')->name('logout-dash');
Route::get('/login', 'HomeController@index')->name('home');
Route::get('/', 'WebController@index');
Route::get('/projects-show', 'WebController@projectsShow')->name('projects-show');
Route::get('/profile', 'WebController@profile');
Route::get('/category/{id}', 'WebController@categoryDeatil')->name('category-detail');
Route::get('/profile/{id}', 'WebController@profile')->name('profile');

Route::get('/about-us', 'WebController@AboutUs')->name('about-us');
Route::get('/contact-us', 'WebController@ContactUs')->name('about-us');
Auth::routes();



Route::group(['as'=>'admin.','middleware'=>['auth','admin'],'prefix'=>'admin'],function (){

    Route::get('/sliders', 'AdminController@Slider')->name('sliders');
    Route::get('/sliders-create', 'AdminController@SliderCreate')->name('slider-create');
    Route::post('/create-sliders', 'AdminController@CreateSlider')->name('add-slider');
    Route::get('/delete-sliders/{id}', 'AdminController@DelSlider')->name('delete-slider');
    Route::get('/edit-sliders/{id}', 'AdminController@EditSlider')->name('edit-slider');
    Route::post('/edit-sliders/{id}', 'AdminController@UpdateSlider')->name('update-slider');


    Route::get('/projects', 'ProjctController@Project')->name('projects');
    Route::get('/projects-create', 'ProjctController@ProjectCreate')->name('project-create');
    Route::post('/create-projects', 'ProjctController@CreateProject')->name('add-project');
    Route::get('/delete-projects/{id}', 'ProjctController@DelProject')->name('delete-project');
    Route::get('/edit-projects/{id}', 'ProjctController@EditProject')->name('edit-project');
    Route::post('/edit-projects/{id}', 'ProjctController@UpdateProject')->name('update-project');



    Route::get('/dashboard','AdminController@dashboard')->name('dashboard');
    Route::get('category/delete/{id}','DeleteController@delCategory')->name('delete-category');
    Route::get('/labour','LabourController@createLabour')->name('labourcreate');
    Route::get('labour/delete/{id}','DeleteController@delLabour')->name('delete-labour');


    Route::post('labour/{id}','LabourController@uppdateLabour')->name('updateLabour');
    Route::resource('labour','LabourController');
    Route::get('/edit-labour/{id}','AdminController@editlabour')->name('editLabour');

    Route::resource('category','CategoryController');





});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('admin.layouts.header-script')
</head>

<body class="no-skin">
@include('admin.layouts.header')

<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
        <script type="text/javascript">
            try{ace.settings.loadState('sidebar')}catch(e){}
        </script>

        <div class="sidebar-shortcuts" id="sidebar-shortcuts">
            <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
                <button class="btn btn-success">
                    <i class="ace-icon fa fa-signal"></i>
                </button>

                <button class="btn btn-info">
                    <i class="ace-icon fa fa-pencil"></i>
                </button>

                <button class="btn btn-warning">
                    <i class="ace-icon fa fa-users"></i>
                </button>

                <button class="btn btn-danger">
                    <i class="ace-icon fa fa-cogs"></i>
                </button>
            </div>

            <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
                <span class="btn btn-success"></span>

                <span class="btn btn-info"></span>

                <span class="btn btn-warning"></span>

                <span class="btn btn-danger"></span>
            </div>
        </div><!-- /.sidebar-shortcuts -->

        @include('admin.layouts.lift-manu-bar')<!-- /.nav-list -->

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>

    <!-- /.main-content -->
    @yield('content')

        <!-- Footer Area Start -->
        @include('admin.layouts.footer')
        <!-- Footer Area End -->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>

    @include('admin.layouts.footer-script')
    @yield('script')

</div><!-- /.main-container -->

</body>
</html>

resources/views/admin/layouts/applogin.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    @include('admin.layouts.header-script')
</head>
<body class="no-skin">

<!-- Header Area Start -->
{{--@include('admin.layouts.header')--}}
<!-- Header Area End -->
<!-- Banner Area Start -->

@yield('content')


<!-- Footer Area Start -->
{{--@include('admin.layouts.footer')--}}
<!-- Footer Area End -->


{{--<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">--}}
{{--<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>--}}
{{--</a>--}}
<!-- Wrapper End -->


<!-- basic scripts -->

<!--[if !IE]> -->
@include('admin.layouts.footer-script')
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

            &nbsp; &nbsp;
            <span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
        </div>
    </div>
</div>
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" id="delete-form">
                {{csrf_field()}}
                {{method_field('DELETE')}}
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal">&times;</button>
                    <h4>Delete</h4>
                </div>
                <div class="modal-body">
                    <p> Are you sure to delete?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" type="submit">Delete</button>
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="modal fade" id="delete-modal-category" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="Get" id="delete-form">
                {{csrf_field()}}
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal">&times;</button>
                    <h4>Delete</h4>
                </div>
                <div class="modal-body">
                    <p> Are you sure to delete this Category?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" type="submit">Delete</button>
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/layouts/header-script.blade.php
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta charset="utf-8" />
<title>Labour Hazir</title>

<!-- CSRF Token -->
<meta nadadadcme="csrf-token" content="{{ csrf_token() }}">

<meta name="description" content="Common form elements and layouts" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}" />
<link rel="stylesheet" href="{{asset('assets/font-awesome/4.5.0/css/font-awesome.min.css')}}" />

<!-- page specific plugin styles -->
<link rel="stylesheet" href="{{asset('assets/css/jquery-ui.custom.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/chosen.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-datepicker3.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-timepicker.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/daterangepicker.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-datetimepicker.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-colorpicker.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/summernote/summernote.css')}}" />

<!-- text fonts -->
<link rel="stylesheet" href="{{asset('assets/css/fonts.googleapis.com.css')}}" />

<!-- ace styles -->
<link rel="stylesheet" href="{{asset('assets/css/ace.min.css')}}" class="ace-main-stylesheet" id="main-ace-style" />

<!--[if lte IE 9]>
<link rel="stylesheet" href="{{asset('assets/css/ace-part2.min.css')}}" class="ace-main-stylesheet" />
<![endif]-->
<link rel="stylesheet" href="{{asset('assets/css/ace-skins.min.css')}}" />
<link rel="stylesheet" href="{{asset('assets/css/ace-rtl.min.css')}}" />

<!--[if lte IE 9]>
<link rel="stylesheet" href="{{asset('assets/css/ace-ie.min.css')}}" />

<![endif]-->

<!-- inline styles related to this page -->

<!-- ace settings handler -->
<script src="{{asset('assets/js/ace-extra.min.js')}}"></script>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
<script src="{{asset('assets/js/html5shiv.min.js')}}"></script>
<script src="{{asset('assets/js/respond.min.js')}}"></script>
<![endif]-->

@yield('style')

resources/views/admin/layouts/lift-manu-bar.blade.php
<ul class="nav nav-list">
    <li class="@if(request()->url() == route('admin.dashboard')){{'active'}}@endif">
        <a href="{{route('admin.dashboard')}}">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> Dashboard </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="@if(request()->url() == route('admin.category.index')){{'active open'}}
    @elseif(request()->url() == route('admin.category.create')){{'active open'}}
    @endif">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
								Category
							</span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="@if(request()->url() == route('admin.category.create')){{'active open'}}@endif">
                <a href="{{route('admin.category.create')}}">
                    <i class="menu-icon fa fa-plus purple"></i>
                    Add Category
                </a>

                <b class="arrow"></b>
            </li>

            <li class="@if(request()->url() == route('admin.category.index')){{'active open'}}@endif">
                <a href="{{route('admin.category.index')}}">
                    <i class="menu-icon fa fa-eye pink"></i>
                    Show Category
                </a>

                <b class="arrow"></b>
            </li>

        </ul>
    </li>

    <li class="@if(request()->url() == route('admin.labour.index')){{'active open'}}
    @elseif(request()->url() == route('admin.labour.create')){{'active open'}}
    @endif">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Labour </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="@if(request()->url()==route('admin.labour.create')){{'active open'}}@endif">
                <a href="{{route('admin.labour.create')}}">
                    <i class="menu-icon fa fa-plus purple"></i>
                    Add Labour
                </a>

                <b class="arrow"></b>
            </li>

            <li class="@if(request()->url()==route('admin.labour.index')){{'active open'}}@endif">
                <a href="{{route('admin.labour.index')}}">
                    <i class="menu-icon fa fa-eye pink"></i>
                    Show Labour
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>

    <li class="@if(request()->url() == route('admin.sliders')){{'active open'}}@elseif(request()->url() == route('admin.slider-create')){{'active open'}}@endif">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Slider </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="@if(request()->url()==route('admin.slider-create')){{'active open'}}@endif">
                <a href="{{route('admin.slider-create')}}">
                    <i class="menu-icon fa fa-plus purple"></i>
                    Add Slider
                </a>

                <b class="arrow"></b>
            </li>

            <li class="@if(request()->url()==route('admin.sliders')){{'active open'}}@endif">
                <a href="{{route('admin.sliders')}}">
                    <i class="menu-icon fa fa-eye pink"></i>
                    Show Slider
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>
    <li class="@if(request()->url() == route('admin.projects')){{'active open'}}@elseif(request()->url() == route('admin.project-create')){{'active open'}}@endif">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Projects </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="@if(request()->url()==route('admin.project-create')){{'active open'}}@endif">
                <a href="{{route('admin.project-create')}}">
                    <i class="menu-icon fa fa-plus purple"></i>
                    Add Projects
                </a>

                <b class="arrow"></b>
            </li>

            <li class="@if(request()->url()==route('admin.projects')){{'active open'}}@endif">
                <a href="{{route('admin.projects')}}">
                    <i class="menu-icon fa fa-eye pink"></i>
                    Show Projects
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>


</ul><!-- /.nav-list -->

resources/views/admin/layouts/navbar.blade.php
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="#">Home</a>
        </li>
        <li class="active">Dashboard TechnologyPoolFoundation</li>
    </ul><!-- /.breadcrumb -->

</div>