routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/migrate', function () {
    $clearcache = Artisan::call('migrate');
    echo "migrate run<br>";

    $clearview = Artisan::call('view:clear');
    echo "View cleared<br>";

    $clearconfig = Artisan::call('config:cache');
    echo "Config cleared<br>";

    $cleardebugbar = Artisan::call('debugbar:clear');
    echo "Debug Bar cleared<br>";
});

Route::get('/logout', 'HomeController@logout')->name('logout-dash');
Route::get('/login', 'HomeController@index')->name('home');
Route::get('/', 'WebController@index');
Route::get('/projects-show', 'WebController@projectsShow')->name('projects-show');
Route::get('/profile', 'WebController@profile');
Route::get('/category/{id}', 'WebController@categoryDeatil')->name('category-detail');
Route::get('/profile/{id}', 'WebController@profile')->name('profile');

Route::get('/about-us', 'WebController@AboutUs')->name('about-us');
Route::get('/contact-us', 'WebController@ContactUs')->name('about-us');
Auth::routes();



Route::group(['as'=>'admin.','middleware'=>['auth','admin'],'prefix'=>'admin'],function (){

    Route::get('/sliders', 'AdminController@Slider')->name('sliders');
    Route::get('/sliders-create', 'AdminController@SliderCreate')->name('slider-create');
    Route::post('/create-sliders', 'AdminController@CreateSlider')->name('add-slider');
    Route::get('/delete-sliders/{id}', 'AdminController@DelSlider')->name('delete-slider');
    Route::get('/edit-sliders/{id}', 'AdminController@EditSlider')->name('edit-slider');
    Route::post('/edit-sliders/{id}', 'AdminController@UpdateSlider')->name('update-slider');


    Route::get('/projects', 'ProjctController@Project')->name('projects');
    Route::get('/projects-create', 'ProjctController@ProjectCreate')->name('project-create');
    Route::post('/create-projects', 'ProjctController@CreateProject')->name('add-project');
    Route::get('/delete-projects/{id}', 'ProjctController@DelProject')->name('delete-project');
    Route::get('/edit-projects/{id}', 'ProjctController@EditProject')->name('edit-project');
    Route::post('/edit-projects/{id}', 'ProjctController@UpdateProject')->name('update-project');



    Route::get('/dashboard','AdminController@dashboard')->name('dashboard');
    Route::get('category/delete/{id}','DeleteController@delCategory')->name('delete-category');
    Route::get('/labour','LabourController@createLabour')->name('labourcreate');
    Route::get('labour/delete/{id}','DeleteController@delLabour')->name('delete-labour');


    Route::post('labour/{id}','LabourController@uppdateLabour')->name('updateLabour');
    Route::resource('labour','LabourController');
    Route::get('/edit-labour/{id}','AdminController@editlabour')->name('editLabour');

    Route::resource('category','CategoryController');





});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;
use App\User;
class Category extends Model
{


    protected $guarded=[];


    public function products(){
        return $this->belongsToMany('App\Product');
//        return $this->belongsToMany('App\Category','product_category','category_id','id');
    }

    public function users(){
        return $this->belongsToMany('App\User');
//        return $this->belongsToMany('App\Category','product_category','category_id','id');
    }

    public function childrens(){
    return $this->belongsToMany(Category::class,'category_parent','category_id','parent_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::paginate(7);
        return view('admin.categories.index',compact('categories'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();
        return view('admin.categories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//       dd($request->all());
        $request->validate([
            'title'=>'required|min:3',
            'description'=>'required|min:3',
            'thumbnail'=>'required',

        ]);
//        dd($request->all());

        $file = $request->file('thumbnail');
        $destinationPath = 'assets/uploads/category-pics';
        $filename = $file->getClientOriginalName();
        $filename = time() . $filename;
        $file->move($destinationPath, $filename);
        $request->merge(['img' => $filename]);

        $category=Category::create($request->only('title','description','slug','img'));
        $category->childrens()->attach($request->parent_id);
        if($category){
            return  back()->with('message','Category Added Successfully');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories=Category::all();
        return view('admin.categories.create',['categories'=>$categories,'category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
//            $category->title = $request->title;
//            $category->description = $request->title;
//            $category->slug = $request->slug;
//            $category->img = $upimg;
////        $category->slug=$request->slug;
//            //detach all parent Category
//            $category->childrens()->detach();
//            //attach selected parent Category
//            $category->childrens()->attach($request->parent_id);
//            //save  recode to the database
//            $saved = $category->save();
//        }

            $scho = Category::find($category->id);

            if ($file = $request->file('thumbnail')) {
                $destinationPath = 'assets/uploads/category-pics';
                $filename = $file->getClientOriginalName();
                $filename = time() . $filename;
                $file->move($destinationPath, $filename);
                $request->merge(['img' => $filename]);
                @unlink(('assets/uploads/category-pics/' . $scho->img));
            }
                    // detach all parent Category
                     $category->childrens()->detach();
                    //attach selected parent Category
                    $category->childrens()->attach($request->parent_id);
                     $update=$scho->update($request->only('title','description','slug','img'));
                     if($update){
                         return back()->with('message', 'Recode Update Successfully');
                     }

//            return back();





    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="{{route('admin.dashboard')}}">Dashboard</a>
                    </li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="ace-settings-container" id="ace-settings-container">
                    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                        <i class="ace-icon fa fa-cog bigger-130"></i>
                    </div>

                    <div class="ace-settings-box clearfix" id="ace-settings-box">
                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <div class="pull-left">
                                    <select id="skin-colorpicker" class="hide">
                                        <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                                        <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                        <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                        <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                                    </select>
                                </div>
                                <span>&nbsp; Choose Skin</span>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-navbar" autocomplete="off" />
                                <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-sidebar" autocomplete="off" />
                                <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-breadcrumbs" autocomplete="off" />
                                <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" autocomplete="off" />
                                <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
                                <label class="lbl" for="ace-settings-add-container">
                                    Inside
                                    <b>.container</b>
                                </label>
                            </div>
                        </div><!-- /.pull-left -->

                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" autocomplete="off" />
                                <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" autocomplete="off" />
                                <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" autocomplete="off" />
                                <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                            </div>
                        </div><!-- /.pull-left -->
                    </div><!-- /.ace-settings-box -->
                </div><!-- /.ace-settings-container -->

                <div class="page-header">
                    <h1>
                        Category
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                           Show All Categories
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="table-responsive">
                                <table id="simple-table" class="table  table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th class="center">
                                            No
                                        </th>
                                        <th class="center">Category Name</th>
                                        <th class=" center hidden-480">Slug</th>
                                        <th class=" center hidden-480">Parent</th>
                                        <th class=" center hidden-480">Image</th>
                                        <th class="center">Description</th>
                                        <th class="center hidden-480">Status</th>
                                        <th class="center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $key=> $category  )
                                    <tr>


                                        <td class="center">
                                            {{($categories->currentpage() - 1) * $categories->perpage() + 1 + $key}}
                                        </td>
                                        <td class="center">{{$category->title}}</td>
                                        <td class="center">{{$category->slug}}</td>
                                        <td class="center">
                                            @if($category->childrens()->count()>0)
                                                @foreach($category->childrens as $children)
                                                    {{$children->title}},
                                                @endforeach
                                            @else
                                                <strong>{{'Parent Category'}}</strong>
                                            @endif
                                        </td>
                                        <td class="center">
                                            @if(isset($category->img))
                                                <img src="{{ asset('assets/uploads/category-pics/'.$category->img) }}"
                                                     width="60px" height="60px">
                                            @else
                                                <strong>{{'Parent Category'}}</strong>
                                            @endif
                                        </td>
                                        <td class=" center hidden-480">{!! $category->description !!}</td>
                                        <td class="center hidden-480">
                                            <span class="label label-sm label-warning">Enable</span>
                                        </td>

                                        <td class="center">
                                            <div class="hidden-sm hidden-xs btn-group">
                                                {{--<button class="btn btn-xs btn-success">--}}
                                                    {{--<i class="ace-icon fa fa-check bigger-120"></i>--}}
                                                {{--</button>--}}

                                                <a href="{{route('admin.category.edit',$category->id)}}" class="btn btn-xs btn-info">
                                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                </a>

                                                <a href="{{route('admin.delete-category',$category->id)}}" class="btn btn-xs btn-danger" title="Delete" type="button">
                                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                </a>

                                                {{--<button class="btn btn-xs btn-warning">--}}
                                                    {{--<i class="ace-icon fa fa-flag bigger-120"></i>--}}
                                                {{--</button>--}}
                                            </div>
                                            <div class="hidden-md hidden-lg">
                                                <div class="inline pos-rel">
                                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                                    </button>

                                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                        {{--<li>--}}
                                                            {{--<a href="#" class="tooltip-info" data-rel="tooltip" title="View">--}}
																			{{--<span class="blue">--}}
																				{{--<i class="ace-icon fa fa-search-plus bigger-120"></i>--}}
																			{{--</span>--}}
                                                            {{--</a>--}}
                                                        {{--</li>--}}

                                                        <li>
                                                            <a href="{{route('admin.category.edit',$category->id)}}" class="tooltip-success" data-rel="tooltip" title="Edit">
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																			</span>
                                                            </a>
                                                        </li>

                                                        <li>
                                                            <a href="{{route('admin.delete-category',$category->id)}}" class="btn btn-xs btn-danger" title="Delete" type="button">
                                                                <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </td>


                                    </tr>
                                    @endforeach
                                    </tbody>

                                </table>
                                </div>
                                <div class="text-left">{{ $categories->links() }}</div>
                            </div><!-- /.span -->
                        </div><!-- /.row -->

                        <div class="hr hr-18 dotted hr-double"></div>

                    <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div>
@endsection